version: '3'

services:
  app:
    image: qqpy3ko/devops-for-programmers-project-74:latest
    build: 
      context: ./
      dockerfile: Dockerfile.production
    environment:
      - NODE_ENV=test
    command: npx sequelize-cli init && npm test