version: '3'

services:
  app:
    depends_on: 
      - db
    image: qqpy3ko/devops-for-programmers-project-74:latest
    build: 
      context: ./
      dockerfile: Dockerfile.production
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    command: bash -c "sleep 3 && npm test"
  db:
    image: postgres:16
    volumes:
      - /db:/var/lib/postgresql/data
    restart:  unless-stopped
    environment:     
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: db