version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
    ports:
      - "8081:8080"
    command: npm run dev