name: push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub

        uses: docker/login-action@v3

        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image

        uses: docker/build-push-action@v5

        with:
          file: ../../app/Dockerfile.production
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/devops-for-programmers-project-74:latest
          cache-to: type=inline
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-for-programmers-project-74:latest

      - name: Make Tests
        run: |
          docker-compose -f ./app/docker-compose.yml up --abort-on-container-exit

      - name: Push

        uses: docker/build-push-action@v5
        
        with:
          file: ../../app/Dockerfile.production
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/devops-for-programmers-project-74:latest
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-for-programmers-project-74:latest